# [metadata]
settings_file_name = "settings.toml"

# [directories]
DATA_DIR = "data/"
DATASET_DIR = "data/datasets/"
LOGS_DIR = 'logs/'
MODELS_DIR = 'data/models/'
GRAPHS_DIR = 'data/graphs/' 
REPORTS_DIR = 'reports/'

# [creation.files]
PLAYERS_NAME = "nba_players.csv"
PLAYERS_BASIC_NAME = "nba_players_basic.csv"
PLAYERS_ADVANCED_NAME = "nba_players_advanced.csv"

# [dataset.files]
DATA_FILE_NAME = "nba_player_stats.csv"
DATA_FILE_5YEAR_NAME = "nba_player_stats_5years.csv"
DATA_FILE_5YEAR_TENSOR_NAME = "nba_player_stats_5years_tensor_ready.csv"
DATA_FILE_5YEAR_OVERLAP = "nba_player_stats_5years_overlap.csv"
DATA_FILE_5YEAR_JSON_NAME = "nba_player_stats_5years.json"

# [models.variables]
FILTER_AMT = 5
