settings_file_name = "settings.toml"

# File data locations
DATA_DIR = "data/"
LOGS_DIR = 'logs/'
MODELS_DIR = 'data/models/'
GRAPHS_DIR = 'data/graphs/' 

# File data names
DATA_FILE_NAME = "data/nba_player_stats.csv"
DATA_FILE_5YEAR_NAME = "data/nba_player_stats_5years.csv"
DATA_FILE_5YEAR_TENSOR_NAME = "data/nba_player_stats_5years_tensor_ready.csv"
DATA_FILE_5YEAR_JSON_NAME = "data/nba_player_stats_5years.json"